/**
 * WordPress dependencies
 */
import { __ } from "@wordpress/i18n";
import {
    addCard,
    addSubmenu,
    alignCenter,
    alignJustify,
    alignLeft,
    alignNone,
    alignRight,
    archive,
    arrowDown,
    arrowLeft,
    arrowRight,
    arrowUp,
    atSymbol,
    aspectRatio,
    audio,
    backup,
    blockDefault,
    blockTable,
    box,
    brush,
    bug,
    button,
    buttons,
    calendar,
    cancelCircleFilled,
    capturePhoto,
    captureVideo,
    category,
    chartBar,
    check,
    chevronDown,
    chevronLeft,
    chevronRight,
    chevronRightSmall,
    chevronUp,
    classic,
    close,
    closeSmall,
    cloudUpload,
    cloud,
    code,
    cog,
    color,
    column,
    columns,
    comment,
    commentAuthorAvatar,
    commentAuthorName,
    commentContent,
    commentReplyLink,
    cover,
    create,
    crop,
    currencyDollar,
    currencyEuro,
    currencyPound,
    customPostType,
    desktop,
    dragHandle,
    download,
    external,
    file,
    flipHorizontal,
    flipVertical,
    formatBold,
    formatCapitalize,
    formatIndent,
    formatIndentRTL,
    formatItalic,
    formatListBullets,
    formatListBulletsRTL,
    formatListNumbered,
    formatListNumberedRTL,
    formatLtr,
    formatLowercase,
    formatOutdent,
    formatOutdentRTL,
    formatStrikethrough,
    formatUnderline,
    formatUppercase,
    fullscreen,
    gallery,
    globe,
    grid,
    group,
    handle,
    heading,
    help,
    helpFilled,
    inbox,
    institution,
    home,
    html,
    image,
    info,
    insertAfter,
    insertBefore,
    justifyLeft,
    justifyCenter,
    justifyRight,
    justifySpaceBetween,
    key,
    keyboardClose,
    keyboardReturn,
    layout,
    lifesaver,
    // There are some issues with these icons.
    // lineDashed,
    // lineDotted,
    // lineSolid,
    link,
    linkOff,
    list,
    listView,
    lock,
    login,
    loop,
    mapMarker,
    media,
    mediaAndText,
    megaphone,
    menu,
    mobile,
    more,
    moreHorizontal,
    moreVertical,
    moveTo,
    navigation,
    overlayText,
    pageBreak,
    customLink,
    page,
    pages,
    paragraph,
    payment,
    percent,
    positionCenter,
    positionLeft,
    positionRight,
    pencil,
    people,
    pin,
    plugins,
    plusCircleFilled,
    plusCircle,
    plus,
    post,
    postAuthor,
    postCategories,
    postContent,
    postComments,
    postCommentsCount,
    postCommentsForm,
    postDate,
    postExcerpt,
    postFeaturedImage,
    postList,
    postTerms,
    previous,
    next,
    preformatted,
    pullLeft,
    pullRight,
    pullquote,
    queryPagination,
    queryPaginationNext,
    queryPaginationNumbers,
    queryPaginationPrevious,
    quote,
    receipt,
    redo,
    removeBug,
    removeSubmenu,
    replace,
    reset,
    resizeCornerNE,
    reusableBlock,
    rotateLeft,
    rotateRight,
    row,
    rss,
    search,
    separator,
    settings,
    share,
    shield,
    shortcode,
    siteLogo,
    stack,
    starEmpty,
    starFilled,
    starHalf,
    store,
    stretchFullWidth,
    styles,
    shipping,
    stretchWide,
    subscript,
    superscript,
    swatch,
    symbol,
    symbolFilled,
    tableColumnAfter,
    tableColumnBefore,
    tableColumnDelete,
    tableRowAfter,
    tableRowBefore,
    tableRowDelete,
    table,
    tag,
    termDescription,
    footer,
    header,
    sidebar,
    textColor,
    tablet,
    tip,
    title,
    tool,
    trash,
    trendingDown,
    trendingUp,
    typography,
    undo,
    ungroup,
    unlock,
    update,
    upload,
    verse,
    video,
    widget,
} from "@wordpress/icons";

/**
 * Internal dependencies
 */
import {
    amazon,
    bandcamp,
    behance,
    chain,
    codepen,
    deviantart,
    dribbble,
    dropbox,
    etsy,
    facebook,
    feed,
    fivehundredpx,
    flickr,
    foursquare,
    goodreads,
    google,
    github,
    instagram,
    lastfm,
    linkedin,
    mail,
    mastodon,
    meetup,
    medium,
    patreon,
    pinterest,
    pocket,
    redditSolid,
    reddit,
    skype,
    snapchat,
    soundcloud,
    spotify,
    telegram,
    tiktok,
    tumblr,
    twitch,
    twitter,
    vimeo,
    vk,
    wordpress,
    yelp,
    youtube,
} from "./wordpress/social";
import { fontAwesomeCategories, fontAwesomeIcons } from "./font-awesome";

// Temporary icon specifications that are not yet in the NPM package.
import { commentEditLink, sparkles } from "./wordpress/temp";

import * as custom from "./custom";

const wordpressSocialIcons = [
    {
        isDefault: true,
        name: "wordpress",
        title: "WordPress",
        type: "wordpress",
        icon: wordpress,
        categories: ["logos"],
    },
    {
        name: "fivehundredpx",
        title: "500px",
        type: "wordpress",
        icon: fivehundredpx,
        categories: ["logos"],
    },
    {
        name: "amazon",
        title: "Amazon",
        type: "wordpress",
        icon: amazon,
        categories: ["logos"],
    },
    {
        name: "bandcamp",
        title: "Bandcamp",
        type: "wordpress",
        icon: bandcamp,
        categories: ["logos"],
    },
    {
        name: "behance",
        title: "Behance",
        type: "wordpress",
        icon: behance,
        categories: ["logos"],
    },
    {
        name: "chain",
        title: "Link",
        type: "wordpress",
        icon: chain,
    },
    {
        name: "codepen",
        title: "CodePen",
        type: "wordpress",
        icon: codepen,
        categories: ["logos"],
    },
    {
        name: "deviantart",
        title: "DeviantArt",
        type: "wordpress",
        icon: deviantart,
        categories: ["logos"],
    },
    {
        name: "dribbble",
        title: "Dribbble",
        type: "wordpress",
        icon: dribbble,
        categories: ["logos"],
    },
    {
        name: "dropbox",
        title: "Dropbox",
        type: "wordpress",
        icon: dropbox,
        categories: ["logos"],
    },
    {
        name: "etsy",
        title: "Etsy",
        type: "wordpress",
        icon: etsy,
        categories: ["logos"],
    },
    {
        name: "facebook",
        title: "Facebook",
        type: "wordpress",
        icon: facebook,
        categories: ["logos"],
    },
    {
        name: "feed",
        title: "RSS Feed",
        type: "wordpress",
        icon: feed,
        categories: ["logos"],
    },
    {
        name: "flickr",
        title: "Flickr",
        type: "wordpress",
        icon: flickr,
        categories: ["logos"],
    },
    {
        name: "foursquare",
        title: "Foursquare",
        type: "wordpress",
        icon: foursquare,
        categories: ["logos"],
    },
    {
        name: "goodreads",
        title: "Goodreads",
        type: "wordpress",
        icon: goodreads,
        categories: ["logos"],
    },
    {
        name: "google",
        title: "Google",
        type: "wordpress",
        icon: google,
        categories: ["logos"],
    },
    {
        name: "github",
        title: "GitHub",
        type: "wordpress",
        icon: github,
        categories: ["logos"],
    },
    {
        name: "instagram",
        title: "Instagram",
        type: "wordpress",
        icon: instagram,
        categories: ["logos"],
    },
    {
        name: "lastfm",
        title: "Last.fm",
        type: "wordpress",
        icon: lastfm,
        categories: ["logos"],
    },
    {
        name: "linkedin",
        title: "LinkedIn",
        type: "wordpress",
        icon: linkedin,
        categories: ["logos"],
    },
    {
        name: "mail",
        title: "Mail",
        categories: ["email", "e-mail"],
        type: "wordpress",
        icon: mail,
    },
    {
        name: "mastodon",
        title: "Mastodon",
        type: "wordpress",
        icon: mastodon,
        categories: ["logos"],
    },
    {
        name: "meetup",
        title: "Meetup",
        type: "wordpress",
        icon: meetup,
        categories: ["logos"],
    },
    {
        name: "medium",
        title: "Medium",
        type: "wordpress",
        icon: medium,
        categories: ["logos"],
    },
    {
        name: "patreon",
        title: "Patreon",
        type: "wordpress",
        icon: patreon,
        categories: ["logos"],
    },
    {
        name: "pinterest",
        title: "Pinterest",
        type: "wordpress",
        icon: pinterest,
        categories: ["logos"],
    },
    {
        name: "pocket",
        title: "Pocket",
        type: "wordpress",
        icon: pocket,
        categories: ["logos"],
    },
    {
        name: "reddit-solid",
        title: "Reddit Solid",
        type: "wordpress",
        icon: redditSolid,
        categories: ["logos"],
    },
    {
        name: "reddit",
        title: "Reddit",
        type: "wordpress",
        icon: reddit,
        categories: ["logos"],
    },
    {
        name: "skype",
        title: "Skype",
        type: "wordpress",
        icon: skype,
        categories: ["logos"],
    },
    {
        name: "snapchat",
        title: "Snapchat",
        type: "wordpress",
        icon: snapchat,
        categories: ["logos"],
    },
    {
        name: "soundcloud",
        title: "SoundCloud",
        type: "wordpress",
        icon: soundcloud,
        categories: ["logos"],
    },
    {
        name: "spotify",
        title: "Spotify",
        type: "wordpress",
        icon: spotify,
        categories: ["logos"],
    },
    {
        name: "telegram",
        title: "Telegram",
        type: "wordpress",
        icon: telegram,
        categories: ["logos"],
    },
    {
        name: "tiktok",
        title: "TikTok",
        type: "wordpress",
        icon: tiktok,
        categories: ["logos"],
    },
    {
        name: "tumblr",
        title: "Tumblr",
        type: "wordpress",
        icon: tumblr,
        categories: ["logos"],
    },
    {
        name: "twitch",
        title: "Twitch",
        type: "wordpress",
        icon: twitch,
        categories: ["logos"],
    },
    {
        isDefault: true,
        name: "twitter",
        title: "Twitter",
        type: "wordpress",
        icon: twitter,
        categories: ["logos"],
    },
    {
        name: "vimeo",
        title: "Vimeo",
        type: "wordpress",
        icon: vimeo,
        categories: ["logos"],
    },
    {
        name: "vk",
        title: "VK",
        type: "wordpress",
        icon: vk,
        categories: ["logos"],
    },
    {
        name: "yelp",
        title: "Yelp",
        type: "wordpress",
        icon: yelp,
        categories: ["logos"],
    },
    {
        name: "youtube",
        title: "YouTube",
        type: "wordpress",
        icon: youtube,
        categories: ["logos"],
    },
];

const wordpressIcons = [
    {
        name: "addCard",
        title: __("Add Card", "tableberg"),
        type: "wordpress",
        icon: addCard,
    },
    {
        name: "addSubmenu",
        title: __("Add Submenu", "tableberg"),
        type: "wordpress",
        icon: addSubmenu,
        categories: ["arrows"],
    },
    {
        name: "alignCenter",
        title: __("Align Center", "tableberg"),
        type: "wordpress",
        icon: alignCenter,
        categories: ["editor"],
    },
    {
        name: "alignJustify",
        title: __("Align Justify", "tableberg"),
        type: "wordpress",
        icon: alignJustify,
        categories: ["editor"],
    },
    {
        name: "alignLeft",
        title: __("Align Left", "tableberg"),
        type: "wordpress",
        icon: alignLeft,
        categories: ["editor"],
    },
    {
        name: "alignNone",
        title: __("Align None", "tableberg"),
        type: "wordpress",
        icon: alignNone,
        categories: ["editor"],
    },
    {
        name: "alignRight",
        title: __("Align Right", "tableberg"),
        type: "wordpress",
        icon: alignRight,
        categories: ["editor"],
    },
    {
        name: "archive",
        title: __("Archive", "tableberg"),
        type: "wordpress",
        icon: archive,
        categories: ["blocks"],
    },
    {
        name: "arrowDown",
        title: __("Arrow Down", "tableberg"),
        type: "wordpress",
        icon: arrowDown,
        categories: ["arrows"],
    },
    {
        name: "arrowLeft",
        title: __("Arrow Left", "tableberg"),
        type: "wordpress",
        icon: arrowLeft,
        categories: ["arrows"],
    },
    {
        name: "arrowRight",
        title: __("Arrow Right", "tableberg"),
        type: "wordpress",
        icon: arrowRight,
        categories: ["arrows"],
    },
    {
        name: "arrowUp",
        title: __("Arrow Up", "tableberg"),
        type: "wordpress",
        icon: arrowUp,
        categories: ["arrows"],
    },
    {
        name: "atSymbol",
        title: __("At Symbol", "tableberg"),
        type: "wordpress",
        icon: atSymbol,
    },
    {
        name: "aspectRatio",
        title: __("Aspect Ratio", "tableberg"),
        type: "wordpress",
        icon: aspectRatio,
        categories: ["media"],
    },
    {
        name: "audio",
        title: __("Audio", "tableberg"),
        type: "wordpress",
        icon: audio,
        categories: ["media"],
    },
    {
        name: "backup",
        title: __("Backup", "tableberg"),
        type: "wordpress",
        icon: backup,
    },
    {
        name: "blockDefault",
        title: __("Block Default", "tableberg"),
        type: "wordpress",
        icon: blockDefault,
        categories: ["blocks"],
    },
    {
        name: "blockTable",
        title: __("Block Table", "tableberg"),
        type: "wordpress",
        icon: blockTable,
    },
    {
        name: "box",
        title: __("Box", "tableberg"),
        type: "wordpress",
        icon: box,
    },
    {
        name: "brush",
        title: __("Brush", "tableberg"),
        type: "wordpress",
        icon: brush,
    },
    {
        name: "bug",
        title: __("Bug", "tableberg"),
        type: "wordpress",
        icon: bug,
    },
    {
        name: "button",
        title: __("Button", "tableberg"),
        type: "wordpress",
        icon: button,
        categories: ["blocks"],
    },
    {
        name: "buttons",
        title: __("Buttons", "tableberg"),
        type: "wordpress",
        icon: buttons,
        categories: ["blocks"],
    },
    {
        name: "calendar",
        title: __("Calendar", "tableberg"),
        type: "wordpress",
        icon: calendar,
        categories: ["blocks"],
    },
    {
        name: "cancelCircleFilled",
        title: __("Cancel - Circle Filled", "tableberg"),
        type: "wordpress",
        icon: cancelCircleFilled,
    },
    {
        name: "capturePhoto",
        title: __("Capture Photo", "tableberg"),
        type: "wordpress",
        icon: capturePhoto,
        categories: ["media"],
    },
    {
        name: "captureVideo",
        title: __("Capture Video", "tableberg"),
        type: "wordpress",
        icon: captureVideo,
        categories: ["media"],
    },
    {
        name: "category",
        title: __("Category", "tableberg"),
        type: "wordpress",
        icon: category,
        categories: ["blocks"],
    },
    {
        name: "chartBar",
        title: __("Chart Bar", "tableberg"),
        type: "wordpress",
        icon: chartBar,
    },
    {
        name: "check",
        title: __("Check", "tableberg"),
        type: "wordpress",
        icon: check,
    },
    {
        name: "checkCirleOutline",
        title: __("Check Cirle Outline", "tableberg"),
        type: "wordpress",
        icon: custom.checkCircleOutlined,
    },
    {
        name: "chevronDown",
        title: __("Chevron Down", "tableberg"),
        type: "wordpress",
        icon: chevronDown,
        categories: ["arrows"],
    },
    {
        name: "chevronLeft",
        title: __("Chevron Left", "tableberg"),
        type: "wordpress",
        icon: chevronLeft,
        categories: ["arrows"],
    },
    {
        name: "chevronRight",
        title: __("Chevron Right", "tableberg"),
        type: "wordpress",
        icon: chevronRight,
        categories: ["arrows"],
    },
    {
        name: "chevronRightSmall",
        title: __("Chevron Right - Small", "tableberg"),
        type: "wordpress",
        icon: chevronRightSmall,
        categories: ["arrows"],
    },
    {
        name: "chevronUp",
        title: __("Chevron Up", "tableberg"),
        type: "wordpress",
        icon: chevronUp,
        categories: ["arrows"],
    },
    {
        name: "classic",
        title: __("Classic", "tableberg"),
        type: "wordpress",
        icon: classic,
        categories: ["blocks"],
    },
    {
        name: "close",
        title: __("Close", "tableberg"),
        type: "wordpress",
        icon: close,
    },
    {
        name: "closeCirleOutline",
        title: __("Close Cirle Outline", "tableberg"),
        type: "wordpress",
        icon: custom.closeCircleOutlined,
    },
    {
        name: "closeSmall",
        title: __("Close - Small", "tableberg"),
        type: "wordpress",
        icon: closeSmall,
    },
    {
        name: "cloudUpload",
        title: __("Cloud Upload", "tableberg"),
        type: "wordpress",
        icon: cloudUpload,
        categories: ["arrows"],
    },
    {
        name: "cloud",
        title: __("Cloud", "tableberg"),
        type: "wordpress",
        icon: cloud,
    },
    {
        name: "code",
        title: __("Code", "tableberg"),
        type: "wordpress",
        icon: code,
        categories: ["blocks"],
    },
    {
        name: "cog",
        title: __("Cog", "tableberg"),
        type: "wordpress",
        icon: cog,
    },
    {
        name: "color",
        title: __("Color", "tableberg"),
        type: "wordpress",
        icon: color,
    },
    {
        name: "column",
        title: __("Column", "tableberg"),
        type: "wordpress",
        icon: column,
        categories: ["blocks"],
    },
    {
        name: "columns",
        title: __("Columns", "tableberg"),
        type: "wordpress",
        icon: columns,
        categories: ["blocks"],
    },
    {
        name: "comment",
        title: __("Comment", "tableberg"),
        type: "wordpress",
        icon: comment,
        categories: ["blocks"],
    },
    {
        name: "commentAuthorAvatar",
        title: __("Comment Author Avatar", "tableberg"),
        type: "wordpress",
        icon: commentAuthorAvatar,
        categories: ["blocks"],
    },
    {
        name: "commentAuthorName",
        title: __("Comment Author Name", "tableberg"),
        type: "wordpress",
        icon: commentAuthorName,
        categories: ["blocks"],
    },
    {
        name: "commentContent",
        title: __("Comment Content", "tableberg"),
        type: "wordpress",
        icon: commentContent,
        categories: ["blocks"],
    },
    {
        name: "commentEditLink",
        title: __("Comment Edit Link", "tableberg"),
        type: "wordpress",
        icon: commentEditLink,
        categories: ["blocks"],
    },
    {
        name: "commentReplyLink",
        title: __("Comment Reply Link", "tableberg"),
        type: "wordpress",
        icon: commentReplyLink,
        categories: ["blocks"],
    },
    {
        name: "cover",
        title: __("Cover", "tableberg"),
        type: "wordpress",
        icon: cover,
        categories: ["blocks"],
    },
    {
        name: "create",
        title: __("Create", "tableberg"),
        type: "wordpress",
        icon: create,
    },
    {
        name: "crop",
        title: __("Crop", "tableberg"),
        type: "wordpress",
        icon: crop,
    },
    {
        name: "currencyDollar",
        title: __("Currency Dollar", "tableberg"),
        type: "wordpress",
        icon: currencyDollar,
    },
    {
        name: "currencyEuro",
        title: __("Currency Euro", "tableberg"),
        type: "wordpress",
        icon: currencyEuro,
    },
    {
        name: "currencyPound",
        title: __("Currency Pound", "tableberg"),
        type: "wordpress",
        icon: currencyPound,
    },
    {
        name: "customPostType",
        title: __("Custom Post Type", "tableberg"),
        type: "wordpress",
        icon: customPostType,
    },
    {
        name: "desktop",
        title: __("Desktop", "tableberg"),
        type: "wordpress",
        icon: desktop,
        categories: ["devices"],
    },
    {
        name: "dragHandle",
        title: __("Drag Handle", "tableberg"),
        type: "wordpress",
        icon: dragHandle,
    },
    {
        name: "download",
        title: __("Download", "tableberg"),
        type: "wordpress",
        icon: download,
        categories: ["arrows"],
    },
    {
        name: "external",
        title: __("External", "tableberg"),
        type: "wordpress",
        icon: external,
    },
    {
        name: "file",
        title: __("File", "tableberg"),
        type: "wordpress",
        icon: file,
    },
    {
        name: "flipHorizontal",
        title: __("Flip Horizontal", "tableberg"),
        type: "wordpress",
        icon: flipHorizontal,
    },
    {
        name: "flipVertical",
        title: __("Flip Vertical", "tableberg"),
        type: "wordpress",
        icon: flipVertical,
    },
    {
        name: "formatBold",
        title: __("Format Bold", "tableberg"),
        type: "wordpress",
        icon: formatBold,
        categories: ["editor"],
    },
    {
        name: "formatCapitalize",
        title: __("Format Capitalize", "tableberg"),
        type: "wordpress",
        icon: formatCapitalize,
        categories: ["editor"],
    },
    {
        name: "formatIndent",
        title: __("Format Indent", "tableberg"),
        type: "wordpress",
        icon: formatIndent,
        categories: ["editor"],
    },
    {
        name: "formatIndentRTL",
        title: __("Format Indent RTL", "tableberg"),
        type: "wordpress",
        icon: formatIndentRTL,
    },
    {
        name: "formatItalic",
        title: __("Format Italic", "tableberg"),
        type: "wordpress",
        icon: formatItalic,
        categories: ["editor"],
    },
    {
        name: "formatListBullets",
        title: __("Format List Bullets", "tableberg"),
        type: "wordpress",
        icon: formatListBullets,
        categories: ["editor"],
    },
    {
        name: "formatListBulletsRTL",
        title: __("Format List Bullets RTL", "tableberg"),
        type: "wordpress",
        icon: formatListBulletsRTL,
        categories: ["editor"],
    },
    {
        name: "formatListNumbered",
        title: __("Format List Numbered", "tableberg"),
        type: "wordpress",
        icon: formatListNumbered,
        categories: ["editor"],
    },
    {
        name: "formatListNumberedRTL",
        title: __("Format List Numbered RTL", "tableberg"),
        type: "wordpress",
        icon: formatListNumberedRTL,
        categories: ["editor"],
    },
    {
        name: "formatLtr",
        title: __("Format LTR", "tableberg"),
        type: "wordpress",
        icon: formatLtr,
        categories: ["editor"],
    },
    {
        name: "formatLowercase",
        title: __("Format Lowercase", "tableberg"),
        type: "wordpress",
        icon: formatLowercase,
        categories: ["editor"],
    },
    {
        name: "formatOutdent",
        title: __("Format Outdent", "tableberg"),
        type: "wordpress",
        icon: formatOutdent,
        categories: ["editor"],
    },
    {
        name: "formatOutdentRTL",
        title: __("Format Outdent RTL", "tableberg"),
        type: "wordpress",
        icon: formatOutdentRTL,
        categories: ["editor"],
    },
    {
        name: "formatStrikethrough",
        title: __("Format Strikethrough", "tableberg"),
        type: "wordpress",
        icon: formatStrikethrough,
        categories: ["editor"],
    },
    {
        name: "formatUnderline",
        title: __("Format Underline", "tableberg"),
        type: "wordpress",
        icon: formatUnderline,
        categories: ["editor"],
    },
    {
        name: "formatUppercase",
        title: __("Format Uppercase", "tableberg"),
        type: "wordpress",
        icon: formatUppercase,
        categories: ["editor"],
    },
    {
        name: "fullscreen",
        title: __("Fullscreen", "tableberg"),
        type: "wordpress",
        icon: fullscreen,
        categories: ["editor"],
    },
    {
        name: "gallery",
        title: __("Gallery", "tableberg"),
        type: "wordpress",
        icon: gallery,
        categories: ["blocks", "media"],
    },
    {
        name: "globe",
        title: __("Globe", "tableberg"),
        type: "wordpress",
        icon: globe,
    },
    {
        name: "grid",
        title: __("Grid", "tableberg"),
        type: "wordpress",
        icon: grid,
    },
    {
        name: "group",
        title: __("Group", "tableberg"),
        type: "wordpress",
        icon: group,
        categories: ["blocks"],
    },
    {
        name: "handle",
        title: __("Handle", "tableberg"),
        type: "wordpress",
        icon: handle,
    },
    {
        name: "heading",
        title: __("Heading", "tableberg"),
        type: "wordpress",
        icon: heading,
        categories: ["blocks"],
    },
    {
        name: "help",
        title: __("Help", "tableberg"),
        type: "wordpress",
        icon: help,
    },
    {
        name: "helpFilled",
        title: __("Help - Filled", "tableberg"),
        type: "wordpress",
        icon: helpFilled,
    },
    {
        name: "inbox",
        title: __("Inbox", "tableberg"),
        type: "wordpress",
        icon: inbox,
    },
    {
        name: "institution",
        title: __("Institution", "tableberg"),
        type: "wordpress",
        icon: institution,
    },
    {
        name: "home",
        title: __("Home", "tableberg"),
        type: "wordpress",
        icon: home,
        categories: ["blocks"],
    },
    {
        name: "html",
        title: __("HTML", "tableberg"),
        type: "wordpress",
        icon: html,
        categories: ["blocks"],
    },
    {
        isDefault: true,
        name: "image",
        title: __("Image", "tableberg"),
        type: "wordpress",
        icon: image,
        categories: ["blocks", "media"],
    },
    {
        name: "info",
        title: __("Info", "tableberg"),
        type: "wordpress",
        icon: info,
    },
    {
        name: "insertAfter",
        title: __("Insert After", "tableberg"),
        type: "wordpress",
        icon: insertAfter,
        categories: ["editor"],
    },
    {
        name: "insertBefore",
        title: __("Insert Before", "tableberg"),
        type: "wordpress",
        icon: insertBefore,
        categories: ["editor"],
    },
    {
        name: "justifyLeft",
        title: __("Justify Left", "tableberg"),
        type: "wordpress",
        icon: justifyLeft,
        categories: ["editor"],
    },
    {
        name: "justifyCenter",
        title: __("Justify Center", "tableberg"),
        type: "wordpress",
        icon: justifyCenter,
        categories: ["editor"],
    },
    {
        name: "justifyRight",
        title: __("Justify Right", "tableberg"),
        type: "wordpress",
        icon: justifyRight,
        categories: ["editor"],
    },
    {
        name: "justifySpaceBetween",
        title: __("Justify Space Between", "tableberg"),
        type: "wordpress",
        icon: justifySpaceBetween,
        categories: ["editor"],
    },
    {
        name: "key",
        title: __("Key", "tableberg"),
        type: "wordpress",
        icon: key,
    },
    {
        name: "keyboardClose",
        title: __("Keyboard Close", "tableberg"),
        type: "wordpress",
        icon: keyboardClose,
        categories: ["editor"],
    },
    {
        name: "keyboardReturn",
        title: __("Keyboard Return", "tableberg"),
        type: "wordpress",
        icon: keyboardReturn,
        categories: ["editor"],
    },
    {
        name: "layout",
        title: __("Layout", "tableberg"),
        type: "wordpress",
        icon: layout,
    },
    {
        name: "lifesaver",
        title: __("Lifesaver", "tableberg"),
        type: "wordpress",
        icon: lifesaver,
    },
    // There are some issues with these icons.
    // {
    // 	name: 'lineDashed',
    // 	title:  __( 'Line Dashed', 'tableberg' ),
    // 	type:"wordpress",
    // 	icon: lineDashed,
    // },
    // {
    // 	name: 'lineDotted',
    // 	title:  __( 'Line Dotted', 'tableberg' ),
    // 	type:"wordpress",
    // 	icon: lineDotted,
    // },
    // {
    // 	name: 'lineSolid',
    // 	title:  __( 'Line Solid', 'tableberg' ),
    // 	type:"wordpress",
    // 	icon: lineSolid,
    // },
    {
        name: "link",
        title: __("Link", "tableberg"),
        type: "wordpress",
        icon: link,
        categories: ["editor"],
    },
    {
        name: "linkOff",
        title: __("Link Off", "tableberg"),
        type: "wordpress",
        icon: linkOff,
        categories: ["editor"],
    },
    {
        name: "list",
        title: __("List", "tableberg"),
        type: "wordpress",
        icon: list,
        categories: ["blocks"],
    },
    {
        name: "listView",
        title: __("List View", "tableberg"),
        type: "wordpress",
        icon: listView,
        categories: ["editor"],
    },
    {
        name: "lock",
        title: __("Lock", "tableberg"),
        type: "wordpress",
        icon: lock,
        categories: ["editor"],
    },
    {
        name: "login",
        title: __("Login", "tableberg"),
        type: "wordpress",
        icon: login,
    },
    {
        name: "loop",
        title: __("Loop", "tableberg"),
        type: "wordpress",
        icon: loop,
        categories: ["blocks"],
    },
    {
        name: "mapMarker",
        title: __("Map Marker", "tableberg"),
        type: "wordpress",
        icon: mapMarker,
    },
    {
        name: "media",
        title: __("Media", "tableberg"),
        type: "wordpress",
        icon: media,
        categories: ["blocks", "media"],
    },
    {
        name: "mediaAndText",
        title: __("Media & Text", "tableberg"),
        type: "wordpress",
        icon: mediaAndText,
        categories: ["blocks", "media"],
    },
    {
        name: "megaphone",
        title: __("Megaphone", "tableberg"),
        type: "wordpress",
        icon: megaphone,
    },
    {
        name: "menu",
        title: __("Menu", "tableberg"),
        type: "wordpress",
        icon: menu,
    },
    {
        name: "mobile",
        title: __("Mobile", "tableberg"),
        type: "wordpress",
        icon: mobile,
        categories: ["devices"],
    },
    {
        name: "more",
        title: __("More", "tableberg"),
        type: "wordpress",
        icon: more,
    },
    {
        name: "moreHorizontal",
        title: __("More Horizontal", "tableberg"),
        type: "wordpress",
        icon: moreHorizontal,
    },
    {
        name: "moreVertical",
        title: __("More Vertical", "tableberg"),
        type: "wordpress",
        icon: moreVertical,
    },
    {
        name: "moveTo",
        title: __("Move To", "tableberg"),
        type: "wordpress",
        icon: moveTo,
        categories: ["arrows"],
    },
    {
        name: "navigation",
        title: __("Navigation", "tableberg"),
        type: "wordpress",
        icon: navigation,
    },
    {
        name: "overlayText",
        title: __("Overlay Text", "tableberg"),
        type: "wordpress",
        icon: overlayText,
    },
    {
        name: "pageBreak",
        title: __("Page Break", "tableberg"),
        type: "wordpress",
        icon: pageBreak,
    },
    {
        name: "customLink",
        title: __("Custom Link", "tableberg"),
        type: "wordpress",
        icon: customLink,
    },
    {
        name: "page",
        title: __("Page", "tableberg"),
        type: "wordpress",
        icon: page,
    },
    {
        name: "pages",
        title: __("Pages", "tableberg"),
        type: "wordpress",
        icon: pages,
    },
    {
        name: "paragraph",
        title: __("Paragraph", "tableberg"),
        type: "wordpress",
        icon: paragraph,
    },
    {
        name: "payment",
        title: __("Payment", "tableberg"),
        type: "wordpress",
        icon: payment,
    },
    {
        name: "percent",
        title: __("Percent", "tableberg"),
        type: "wordpress",
        icon: percent,
    },
    {
        name: "positionCenter",
        title: __("Position Center", "tableberg"),
        type: "wordpress",
        icon: positionCenter,
    },
    {
        name: "positionLeft",
        title: __("Position Left", "tableberg"),
        type: "wordpress",
        icon: positionLeft,
    },
    {
        name: "positionRight",
        title: __("Position Right", "tableberg"),
        type: "wordpress",
        icon: positionRight,
    },
    {
        name: "post",
        title: __("Post", "tableberg"),
        type: "wordpress",
        icon: post,
    },
    {
        name: "pencil",
        title: __("Pencil", "tableberg"),
        type: "wordpress",
        icon: pencil,
    },
    {
        name: "people",
        title: __("People", "tableberg"),
        type: "wordpress",
        icon: people,
    },
    {
        name: "pin",
        title: __("Pin", "tableberg"),
        type: "wordpress",
        icon: pin,
    },
    {
        name: "plugins",
        title: __("Plugins", "tableberg"),
        type: "wordpress",
        icon: plugins,
    },
    {
        name: "plusCircleFilled",
        title: __("Plus Circle - Filled", "tableberg"),
        type: "wordpress",
        icon: plusCircleFilled,
    },
    {
        name: "plusCircle",
        title: __("Plus Circle", "tableberg"),
        type: "wordpress",
        icon: plusCircle,
    },
    {
        name: "plus",
        title: __("Plus", "tableberg"),
        type: "wordpress",
        icon: plus,
    },
    {
        name: "postAuthor",
        title: __("Post Author", "tableberg"),
        type: "wordpress",
        icon: postAuthor,
        categories: ["blocks"],
    },
    {
        name: "postCategories",
        title: __("Post Categories", "tableberg"),
        type: "wordpress",
        icon: postCategories,
        categories: ["blocks"],
    },
    {
        name: "postContent",
        title: __("Post Content", "tableberg"),
        type: "wordpress",
        icon: postContent,
        categories: ["blocks"],
    },
    {
        name: "postComments",
        title: __("Post Comments", "tableberg"),
        type: "wordpress",
        icon: postComments,
        categories: ["blocks"],
    },
    {
        name: "postCommentsCount",
        title: __("Post Comment Count", "tableberg"),
        type: "wordpress",
        icon: postCommentsCount,
    },
    {
        name: "postCommentsForm",
        title: __("Post Comments Form", "tableberg"),
        type: "wordpress",
        icon: postCommentsForm,
        categories: ["blocks"],
    },
    {
        name: "postDate",
        title: __("Post Date", "tableberg"),
        type: "wordpress",
        icon: postDate,
        categories: ["blocks"],
    },
    {
        name: "postExcerpt",
        title: __("Post Excerpt", "tableberg"),
        type: "wordpress",
        icon: postExcerpt,
        categories: ["blocks"],
    },
    {
        name: "postFeaturedImage",
        title: __("Post Featured Image", "tableberg"),
        type: "wordpress",
        icon: postFeaturedImage,
        categories: ["blocks"],
    },
    {
        name: "postList",
        title: __("Post List", "tableberg"),
        type: "wordpress",
        icon: postList,
        categories: ["blocks"],
    },
    {
        name: "postTerms",
        title: __("Post Terms", "tableberg"),
        type: "wordpress",
        icon: postTerms,
        categories: ["blocks"],
    },
    {
        name: "previous",
        title: __("Previous", "tableberg"),
        type: "wordpress",
        icon: previous,
        categories: ["arrows"],
    },
    {
        name: "next",
        title: __("Next", "tableberg"),
        type: "wordpress",
        icon: next,
        categories: ["arrows"],
    },
    {
        name: "preformatted",
        title: __("Preformatted", "tableberg"),
        type: "wordpress",
        icon: preformatted,
    },
    {
        name: "pullLeft",
        title: __("Pull Left", "tableberg"),
        type: "wordpress",
        icon: pullLeft,
    },
    {
        name: "pullRight",
        title: __("Pull Right", "tableberg"),
        type: "wordpress",
        icon: pullRight,
    },
    {
        name: "pullquote",
        title: __("Pull Quote", "tableberg"),
        type: "wordpress",
        icon: pullquote,
    },
    {
        name: "queryPagination",
        title: __("Query Pagination", "tableberg"),
        type: "wordpress",
        icon: queryPagination,
    },
    {
        name: "queryPaginationNext",
        title: __("Query Pagination Next", "tableberg"),
        type: "wordpress",
        icon: queryPaginationNext,
        categories: ["arrows"],
    },
    {
        name: "queryPaginationNumbers",
        title: __("Query Pagination Numbers", "tableberg"),
        type: "wordpress",
        icon: queryPaginationNumbers,
    },
    {
        name: "queryPaginationPrevious",
        title: __("Query Pagination Previous", "tableberg"),
        type: "wordpress",
        icon: queryPaginationPrevious,
        categories: ["arrows"],
    },
    {
        name: "quote",
        title: __("Quote", "tableberg"),
        type: "wordpress",
        icon: quote,
        categories: ["blocks"],
    },
    {
        name: "receipt",
        title: __("Receipt", "tableberg"),
        type: "wordpress",
        icon: receipt,
    },
    {
        name: "redo",
        title: __("Redo", "tableberg"),
        type: "wordpress",
        icon: redo,
        categories: ["arrows", "editor"],
    },
    {
        name: "removeBug",
        title: __("Remove Bug", "tableberg"),
        type: "wordpress",
        icon: removeBug,
    },
    {
        name: "removeSubmenu",
        title: __("Remove Submenu", "tableberg"),
        type: "wordpress",
        icon: removeSubmenu,
    },
    {
        name: "replace",
        title: __("Replace", "tableberg"),
        type: "wordpress",
        icon: replace,
        categories: ["arrows"],
    },
    {
        name: "reset",
        title: __("Reset", "tableberg"),
        type: "wordpress",
        icon: reset,
        categories: ["minus"],
    },
    {
        name: "resizeCornerNE",
        title: __("Resize Corner", "tableberg"),
        type: "wordpress",
        icon: resizeCornerNE,
        categories: ["arrows"],
    },
    {
        name: "reusableBlock",
        title: __("Reusable Block", "tableberg"),
        type: "wordpress",
        icon: reusableBlock,
        categories: ["arrows"],
    },
    {
        name: "rotateLeft",
        title: __("Rotate Left", "tableberg"),
        type: "wordpress",
        icon: rotateLeft,
        categories: ["arrows"],
    },
    {
        name: "rotateRight",
        title: __("Rotate Right", "tableberg"),
        type: "wordpress",
        icon: rotateRight,
        categories: ["arrows"],
    },
    {
        name: "row",
        title: __("Row", "tableberg"),
        type: "wordpress",
        icon: row,
    },
    {
        name: "rss",
        title: __("RSS", "tableberg"),
        type: "wordpress",
        icon: rss,
    },
    {
        name: "search",
        title: __("Search", "tableberg"),
        type: "wordpress",
        icon: search,
        categories: ["magnifying glass"],
    },
    {
        name: "separator",
        title: __("Separator", "tableberg"),
        type: "wordpress",
        icon: separator,
        categories: ["blocks"],
    },
    {
        name: "settings",
        title: __("Settings", "tableberg"),
        type: "wordpress",
        icon: settings,
    },
    {
        name: "share",
        title: __("Share", "tableberg"),
        type: "wordpress",
        icon: share,
    },
    {
        name: "shield",
        title: __("Shield", "tableberg"),
        type: "wordpress",
        icon: shield,
    },
    {
        name: "shortcode",
        title: __("Shortcode", "tableberg"),
        type: "wordpress",
        icon: shortcode,
        categories: ["blocks"],
    },
    {
        name: "siteLogo",
        title: __("Site Logo", "tableberg"),
        type: "wordpress",
        icon: siteLogo,
        categories: ["blocks", "media"],
    },
    {
        isDefault: true,
        name: "sparkles",
        title: __("Sparkles", "tableberg"),
        type: "wordpress",
        icon: sparkles,
    },
    {
        name: "stack",
        title: __("Stack", "tableberg"),
        type: "wordpress",
        icon: stack,
    },
    {
        name: "starEmpty",
        title: __("Star Empty", "tableberg"),
        type: "wordpress",
        icon: starEmpty,
    },
    {
        name: "starFilled",
        title: __("Star Filled", "tableberg"),
        type: "wordpress",
        icon: starFilled,
    },
    {
        name: "starHalf",
        title: __("Star Half", "tableberg"),
        type: "wordpress",
        icon: starHalf,
    },
    {
        name: "store",
        title: __("Store", "tableberg"),
        type: "wordpress",
        icon: store,
    },
    {
        name: "stretchFullWidth",
        title: __("Stretch Full Width", "tableberg"),
        type: "wordpress",
        icon: stretchFullWidth,
        categories: ["editor"],
    },
    {
        name: "styles",
        title: __("Styles", "tableberg"),
        type: "wordpress",
        icon: styles,
    },
    {
        isDefault: true,
        name: "shipping",
        title: __("Shipping", "tableberg"),
        type: "wordpress",
        icon: shipping,
        categories: ["truck"],
    },
    {
        name: "stretchWide",
        title: __("Stretch Wide", "tableberg"),
        type: "wordpress",
        icon: stretchWide,
        categories: ["editor"],
    },
    {
        name: "subscript",
        title: __("Subscript", "tableberg"),
        type: "wordpress",
        icon: subscript,
        categories: ["editor"],
    },
    {
        name: "superscript",
        title: __("Superscript", "tableberg"),
        type: "wordpress",
        icon: superscript,
        categories: ["editor"],
    },
    {
        name: "swatch",
        title: __("Swatch", "tableberg"),
        type: "wordpress",
        icon: swatch,
    },
    {
        name: "symbol",
        title: __("Symbol", "tableberg"),
        type: "wordpress",
        icon: symbol,
    },
    {
        name: "symbolFilled",
        title: __("Symbol - Filled", "tableberg"),
        type: "wordpress",
        icon: symbolFilled,
    },
    {
        name: "tableColumnAfter",
        title: __("Table Column After", "tableberg"),
        type: "wordpress",
        icon: tableColumnAfter,
        categories: ["editor"],
    },
    {
        name: "tableColumnBefore",
        title: __("Table Column Before", "tableberg"),
        type: "wordpress",
        icon: tableColumnBefore,
        categories: ["editor"],
    },
    {
        name: "tableColumnDelete",
        title: __("Table Column Delete", "tableberg"),
        type: "wordpress",
        icon: tableColumnDelete,
        categories: ["editor"],
    },
    {
        name: "tableRowAfter",
        title: __("Table Row After", "tableberg"),
        type: "wordpress",
        icon: tableRowAfter,
        categories: ["editor"],
    },
    {
        name: "tableRowBefore",
        title: __("Table Row Before", "tableberg"),
        type: "wordpress",
        icon: tableRowBefore,
        categories: ["editor"],
    },
    {
        name: "tableRowDelete",
        title: __("Table Row Delete", "tableberg"),
        type: "wordpress",
        icon: tableRowDelete,
        categories: ["editor"],
    },
    {
        name: "table",
        title: __("Table", "tableberg"),
        type: "wordpress",
        icon: table,
    },
    {
        name: "tag",
        title: __("Tag", "tableberg"),
        type: "wordpress",
        icon: tag,
    },
    {
        name: "termDescription",
        title: __("Term Description", "tableberg"),
        type: "wordpress",
        icon: termDescription,
        categories: ["blocks"],
    },
    {
        name: "footer",
        title: __("Footer", "tableberg"),
        type: "wordpress",
        icon: footer,
    },
    {
        name: "header",
        title: __("Header", "tableberg"),
        type: "wordpress",
        icon: header,
    },
    {
        name: "sidebar",
        title: __("Sidebar", "tableberg"),
        type: "wordpress",
        icon: sidebar,
    },
    {
        name: "textColor",
        title: __("Text Color", "tableberg"),
        type: "wordpress",
        icon: textColor,
    },
    {
        name: "tablet",
        title: __("Tablet", "tableberg"),
        type: "wordpress",
        icon: tablet,
        categories: ["devices"],
    },
    {
        name: "title",
        title: __("Title", "tableberg"),
        type: "wordpress",
        icon: title,
    },
    {
        name: "tip",
        title: __("Tip", "tableberg"),
        type: "wordpress",
        icon: tip,
    },
    {
        name: "tool",
        title: __("Tool", "tableberg"),
        type: "wordpress",
        icon: tool,
    },
    {
        name: "trash",
        title: __("Trash", "tableberg"),
        type: "wordpress",
        icon: trash,
    },
    {
        name: "trendingDown",
        title: __("Trending Down", "tableberg"),
        type: "wordpress",
        icon: trendingDown,
        categories: ["arrows"],
    },
    {
        name: "trendingUp",
        title: __("Trending Up", "tableberg"),
        type: "wordpress",
        icon: trendingUp,
        categories: ["arrows"],
    },
    {
        name: "typography",
        title: __("Typography", "tableberg"),
        type: "wordpress",
        icon: typography,
    },
    {
        name: "undo",
        title: __("Undo", "tableberg"),
        type: "wordpress",
        icon: undo,
        categories: ["arrows", "editor"],
    },
    {
        name: "ungroup",
        title: __("Ungroup", "tableberg"),
        type: "wordpress",
        icon: ungroup,
        categories: ["editor"],
    },
    {
        name: "unlock",
        title: __("Unlock", "tableberg"),
        type: "wordpress",
        icon: unlock,
        categories: ["editor"],
    },
    {
        name: "update",
        title: __("Update", "tableberg"),
        type: "wordpress",
        icon: update,
    },
    {
        name: "upload",
        title: __("Upload", "tableberg"),
        type: "wordpress",
        icon: upload,
        categories: ["arrows"],
    },
    {
        isDefault: true,
        name: "verse",
        title: __("Verse", "tableberg"),
        type: "wordpress",
        icon: verse,
        categories: ["blocks"],
    },
    {
        name: "video",
        title: __("Video", "tableberg"),
        type: "wordpress",
        icon: video,
        categories: ["media"],
    },
    {
        name: "widget",
        title: __("Widget", "tableberg"),
        type: "wordpress",
        icon: widget,
    },
];

export const tablebergIcons = [
    {
        isDefault: false,
        type: "wordpress",
        title: __("WordPress", "tableberg"),
        icons: [...wordpressSocialIcons, ...wordpressIcons],
        categories: [
            {
                name: "arrows",
                title: __("Arrows", "tableberg"),
            },
            {
                name: "blocks",
                title: __("Blocks", "tableberg"),
            },
            {
                name: "devices",
                title: __("Devices", "tableberg"),
            },
            {
                name: "editor",
                title: __("Editor", "tableberg"),
            },
            {
                name: "logos",
                title: __("Logos", "tableberg"),
            },
            {
                name: "media",
                title: __("Media", "tableberg"),
            },
        ],
    },
    {
        isDefault: false,
        type: "font-awesome",
        title: __("Font Awesome", "tableberg"),
        icons: fontAwesomeIcons,
        categories: fontAwesomeCategories,
    },
];
